### PR TITLE
Cleanup: CI, tests, fmt, clippy, just

### PR DESCRIPTION
**Pull request by nyurik**
This does not change code in any significant way, but automated testing using GitHub CI, formats code for consistency, and adds just targets to simplify development.

There were a few clippy fixes that didn't appear too significant.

Relevant changes:
* Exposed `item::ItemType` in public (it is exposed in docs, clippy was complaining)

P.S. Please consider renaming to `main` branch

### CODE REVIEW

**Comment by gammelalf** [comment]
Cool thx.
I'm on vacation right now, but I'll check it out once I'm back.

**Comment by nyurik** [comment]
Thx!  It would be cool to either expose more of the osmium's functionality (e.g. replication server handling, etc), or possibly have a clean rust implementation (not certain if its worth the time though)

**Comment by gammelalf** [comment]
Hi, sorry for taking a while.

yes I agree on both statements. It would be really cool to expose more or reimplement it cleanly. Sadly I don't have time right now to work on it.

**Comment by nyurik** [comment]
thx for merging. If you want, i could try to help with this proj, inculding publishing, etc.

**Pull request merged**
